# Generated by Django 5.2.7 on 2025-10-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=50)),
                ('num_market_pairs', models.IntegerField()),
                ('date_added', models.DateTimeField()),
                ('tags', models.JSONField(blank=True, null=True)),
                ('max_supply', models.FloatField(blank=True, null=True)),
                ('circulating_supply', models.FloatField()),
                ('total_supply', models.FloatField()),
                ('infinite_supply', models.BooleanField(default=False)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('cmc_rank', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
                ('price_usd', models.FloatField()),
                ('price_ngn', models.FloatField()),
            ],
        ),
    ]
